In [8]:
import os
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

os.chdir('/Users/fogellmcmuffin/Documents/thesis/_replication/')    # Working dir

mean_spf_trim = pd.read_csv('cleaned_data/mean_spf_trim.csv')
ind_spf_trim = pd.read_csv('cleaned_data/ind_spf_trim.csv')

mean_spf_trim = mean_spf_trim.set_index('DATE')
ind_spf_trim = ind_spf_trim.set_index(['DATE', 'ID'])
ind_spf_trim = ind_spf_trim.drop(['INDUSTRY'], axis=1)

###############################################
                ## SUM STATS ##
###############################################

def sumstats(df, end_date):
    df = df[:end_date]
    df = df.drop(['CPI1', 'CPI2', 'CPI3', 'CPI4', 'CPI5', 'CPI6', 'rec'], axis=1)
    df = df * 100
    for n in range(0,4):
        df[f'ru_t{n}'] = (df[f'r_t{n}'] > 0).astype(int)
        df[f'rd_t{n}'] = (df[f'r_t{n}'] < 0).astype(int)
        df[f'rn_t{n}'] = (df[f'r_t{n}'] == 0).astype(int)
    return df

date = '2022-12-31'

ind_stats = sumstats(ind_spf_trim, date)
mean_stats = sumstats(mean_spf_trim, date)

In [9]:
print(f"Number of Unique Forecasters: {ind_spf_trim[:date].index.get_level_values('ID').nunique()}")
print(f"Average Forecaster per Forecaster: {np.mean(ind_spf_trim[:date].groupby(level='ID').size())}")

Number of Unique Forecasters: 136
Average Forecaster per Forecaster: 37.088235294117645

In [10]:
ind_stats.describe().round(2)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,5044.00,5044.00,5044.00,5044.00,5044.00,4061.00,4061.00,4061.00,4061.00,5044.00,5044.00,5044.00,5044.00,5044.00,5044.00,5044.00,5044.0,5044.00,5044.00,5044.00,5044.00,5044.00,5044.00,5044.00,5044.00,5044.00
mean,0.66,1.33,2.01,2.72,3.44,-0.01,-0.02,-0.04,-0.05,0.01,0.01,0.00,-0.02,-0.05,0.39,0.42,0.0,0.37,0.40,0.04,0.36,0.42,0.03,0.36,0.42,0.02
std,0.46,0.72,0.98,1.25,1.54,0.39,0.52,0.62,0.71,0.42,0.85,1.21,1.55,1.90,0.49,0.49,0.0,0.48,0.49,0.19,0.48,0.49,0.16,0.48,0.49,0.14
min,-2.07,-2.74,-3.04,-2.72,-2.29,-2.88,-4.04,-5.05,-5.49,-3.60,-5.03,-5.58,-6.54,-9.76,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.45,0.95,1.46,1.99,2.52,-0.15,-0.23,-0.28,-0.33,-0.19,-0.40,-0.63,-0.83,-1.07,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,0.65,1.26,1.89,2.50,3.14,-0.00,0.00,-0.00,-0.01,-0.01,-0.01,-0.08,-0.20,-0.29,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,0.88,1.66,2.44,3.26,4.09,0.15,0.20,0.23,0.25,0.22,0.42,0.56,0.62,0.72,1.00,1.00,0.0,1.00,1.00,0.00,1.00,1.00,0.00,1.00,1.00,0.00
max,2.95,5.83,9.01,12.36,15.90,3.00,3.45,3.48,4.54,2.18,4.14,6.89,7.95,8.73,1.00,1.00,0.0,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [11]:
mean_stats.describe().round(2)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,166.00,166.00,166.00,166.00,166.00,165.00,165.00,165.00,165.00,166.00,166.00,166.00,166.00,166.00,166.00,166.00,166.0,166.00,166.00,166.0,166.00,166.00,166.0,166.00,166.00,166.0
mean,0.72,1.45,2.21,2.98,3.77,-0.01,-0.03,-0.05,-0.07,0.00,-0.00,-0.03,-0.07,-0.13,0.46,0.53,0.0,0.46,0.53,0.0,0.45,0.54,0.0,0.44,0.55,0.0
std,0.41,0.69,0.97,1.27,1.58,0.28,0.37,0.43,0.49,0.33,0.73,1.07,1.39,1.73,0.50,0.50,0.0,0.50,0.50,0.0,0.50,0.50,0.0,0.50,0.50,0.0
min,-0.67,-0.45,-0.05,0.39,0.86,-1.21,-1.72,-1.88,-2.01,-1.82,-2.73,-3.91,-4.12,-4.95,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0
25%,0.51,1.00,1.53,2.12,2.70,-0.09,-0.14,-0.21,-0.25,-0.15,-0.32,-0.55,-0.73,-0.92,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0
50%,0.69,1.36,1.96,2.62,3.27,-0.01,-0.02,-0.03,-0.02,-0.02,-0.05,-0.15,-0.28,-0.39,0.00,1.00,0.0,0.00,1.00,0.0,0.00,1.00,0.0,0.00,1.00,0.0
75%,0.86,1.71,2.61,3.54,4.52,0.10,0.11,0.13,0.15,0.16,0.38,0.44,0.43,0.52,1.00,1.00,0.0,1.00,1.00,0.0,1.00,1.00,0.0,1.00,1.00,0.0
max,2.41,4.47,6.55,8.76,11.09,0.89,1.33,1.54,1.68,1.19,2.50,4.15,5.39,7.43,1.00,1.00,0.0,1.00,1.00,0.0,1.00,1.00,0.0,1.00,1.00,0.0