In [16]:
import os
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

os.chdir('/Users/fogellmcmuffin/Documents/thesis/_replication/')    # Working dir

mean_spf_trim = pd.read_csv('cleaned_data/mean_spf_trim.csv')
ind_spf_trim = pd.read_csv('cleaned_data/ind_spf_trim.csv')

mean_spf_trim = mean_spf_trim.set_index('DATE')
ind_spf_trim = ind_spf_trim.set_index(['DATE', 'ID'])
ind_spf_trim = ind_spf_trim.drop(['INDUSTRY'], axis=1)

###############################################
                ## SUM STATS ##
###############################################

def sumstats(df, end_date):
    df = df[:end_date]
    df = df.drop(['CPI1', 'CPI2', 'CPI3', 'CPI4', 'CPI5', 'CPI6', 'rec'], axis=1)
    df = df * 100
    for n in range(0,4):
        df[f'ru_t{n}'] = (df[f'r_t{n}'] > 0).astype(int)
        df[f'rd_t{n}'] = (df[f'r_t{n}'] < 0).astype(int)
        df[f'rn_t{n}'] = (df[f'r_t{n}'] == 0).astype(int)
    return df

# Data without recessions and COVID aftermath
def no_rec(df):
    a = df['2021-09-30':'2022-09-30']
    b = df[df['rec'] == 1]
    return df[(~df.index.isin(a.index)) & (~df.index.isin(b.index))]

ind_spf_trim_nr = no_rec(ind_spf_trim)
mean_spf_trim_nr = no_rec(mean_spf_trim)

date = '2023-12-31'

ind_stats = sumstats(ind_spf_trim, date)
mean_stats = sumstats(mean_spf_trim, date)
ind_stats_nr = sumstats(ind_spf_trim_nr, date)
mean_stats_nr = sumstats(mean_spf_trim_nr, date)

ind_stats.describe().round(3)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,5160.000,5160.000,5160.000,5160.000,5160.000,4169.000,4169.000,4169.000,4169.000,5160.000,5135.000,5105.000,5074.000,5044.000,5160.000,5160.000,5160.0,5160.000,5160.000,5160.000,5160.000,5160.000,5160.000,5160.000,5160.000,5160.000
mean,0.665,1.336,2.021,2.725,3.443,-0.009,-0.024,-0.040,-0.055,0.008,0.011,-0.000,-0.017,-0.050,0.387,0.421,0.0,0.370,0.403,0.035,0.362,0.418,0.028,0.365,0.424,0.019
std,0.456,0.719,0.976,1.242,1.527,0.386,0.517,0.616,0.706,0.420,0.842,1.205,1.549,1.901,0.487,0.494,0.0,0.483,0.491,0.184,0.481,0.493,0.164,0.482,0.494,0.137
min,-2.074,-2.744,-3.043,-2.724,-2.292,-2.876,-4.038,-5.052,-5.490,-3.602,-5.025,-5.578,-6.543,-9.757,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,0.461,0.952,1.457,1.994,2.525,-0.150,-0.226,-0.279,-0.329,-0.195,-0.395,-0.631,-0.831,-1.074,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
50%,0.650,1.279,1.887,2.523,3.147,-0.000,0.000,-0.001,-0.007,-0.006,-0.012,-0.081,-0.198,-0.288,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
75%,0.875,1.657,2.458,3.264,4.090,0.150,0.201,0.228,0.254,0.220,0.416,0.560,0.622,0.720,1.000,1.000,0.0,1.000,1.000,0.000,1.000,1.000,0.000,1.000,1.000,0.000
max,2.950,5.833,9.008,12.360,15.899,2.996,3.446,3.484,4.536,2.181,4.143,6.889,7.949,8.734,1.000,1.000,0.0,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000

In [17]:
ind_stats_nr.describe().round(3)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,4453.000,4453.000,4453.000,4453.000,4453.000,3600.000,3600.000,3600.000,3600.000,4453.000,4428.000,4398.000,4367.000,4337.000,4453.000,4453.000,4453.0,4453.000,4453.000,4453.000,4453.000,4453.000,4453.000,4453.000,4453.000,4453.000
mean,0.657,1.327,2.017,2.726,3.452,-0.015,-0.036,-0.056,-0.072,-0.004,-0.014,-0.040,-0.059,-0.078,0.373,0.436,0.0,0.356,0.415,0.038,0.347,0.431,0.030,0.352,0.435,0.022
std,0.368,0.623,0.893,1.179,1.482,0.302,0.413,0.514,0.616,0.352,0.669,0.962,1.293,1.707,0.484,0.496,0.0,0.479,0.493,0.190,0.476,0.495,0.171,0.478,0.496,0.146
min,-1.631,-1.561,-1.288,-0.880,-0.944,-2.250,-3.400,-4.323,-5.490,-1.808,-3.304,-4.998,-6.543,-9.757,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,0.468,0.960,1.481,2.015,2.537,-0.150,-0.226,-0.278,-0.321,-0.196,-0.375,-0.594,-0.775,-1.002,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
50%,0.626,1.254,1.872,2.498,3.113,-0.000,-0.000,-0.025,-0.025,-0.019,-0.037,-0.112,-0.202,-0.280,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
75%,0.825,1.609,2.419,3.215,4.039,0.125,0.175,0.178,0.204,0.183,0.327,0.460,0.511,0.656,1.000,1.000,0.0,1.000,1.000,0.000,1.000,1.000,0.000,1.000,1.000,0.000
max,2.950,5.833,9.008,12.360,15.899,1.700,2.380,3.484,4.536,1.958,2.867,4.374,6.116,8.446,1.000,1.000,0.0,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000

In [18]:
mean_stats.describe().round(3)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,170.000,170.000,170.000,170.000,170.000,169.000,169.000,169.000,169.000,170.000,169.000,168.000,167.000,166.000,170.000,170.000,170.0,170.000,170.000,170.0,170.000,170.000,170.0,170.000,170.000,170.0
mean,0.726,1.458,2.208,2.978,3.766,-0.010,-0.030,-0.052,-0.072,0.004,-0.004,-0.031,-0.072,-0.133,0.465,0.529,0.0,0.465,0.529,0.0,0.453,0.541,0.0,0.441,0.553,0.0
std,0.409,0.684,0.963,1.254,1.561,0.274,0.366,0.428,0.488,0.330,0.725,1.062,1.385,1.726,0.500,0.501,0.0,0.500,0.501,0.0,0.499,0.500,0.0,0.498,0.499,0.0
min,-0.667,-0.454,-0.053,0.388,0.861,-1.210,-1.716,-1.881,-2.014,-1.820,-2.735,-3.913,-4.119,-4.946,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0
25%,0.515,1.004,1.542,2.139,2.722,-0.089,-0.144,-0.207,-0.253,-0.148,-0.297,-0.542,-0.725,-0.921,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0
50%,0.700,1.375,2.046,2.650,3.300,-0.010,-0.016,-0.025,-0.023,-0.018,-0.047,-0.151,-0.274,-0.393,0.000,1.000,0.0,0.000,1.000,0.0,0.000,1.000,0.0,0.000,1.000,0.0
75%,0.859,1.701,2.603,3.511,4.507,0.092,0.106,0.135,0.150,0.157,0.365,0.427,0.421,0.524,1.000,1.000,0.0,1.000,1.000,0.0,1.000,1.000,0.0,1.000,1.000,0.0
max,2.411,4.468,6.554,8.762,11.087,0.889,1.333,1.540,1.680,1.195,2.498,4.146,5.393,7.434,1.000,1.000,0.0,1.000,1.000,0.0,1.000,1.000,0.0,1.000,1.000,0.0

In [19]:
mean_stats_nr.describe().round(3)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,147.000,147.000,147.000,147.000,147.000,146.000,146.000,146.000,146.000,147.000,146.000,145.000,144.000,143.000,147.000,147.000,147.0,147.000,147.000,147.0,147.000,147.000,147.0,147.000,147.000,147.0
mean,0.710,1.439,2.192,2.968,3.763,-0.023,-0.050,-0.075,-0.097,-0.013,-0.042,-0.091,-0.139,-0.193,0.449,0.544,0.0,0.449,0.544,0.0,0.435,0.558,0.0,0.422,0.571,0.0
std,0.345,0.625,0.925,1.238,1.564,0.206,0.275,0.334,0.400,0.283,0.580,0.851,1.165,1.570,0.499,0.500,0.0,0.499,0.500,0.0,0.498,0.498,0.0,0.496,0.497,0.0
min,-0.391,-0.007,0.474,0.995,1.512,-0.813,-1.096,-1.442,-2.014,-0.743,-1.922,-2.687,-3.100,-4.946,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0
25%,0.510,1.003,1.535,2.128,2.705,-0.091,-0.153,-0.207,-0.258,-0.146,-0.294,-0.520,-0.695,-0.897,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0
50%,0.678,1.316,1.939,2.611,3.285,-0.012,-0.017,-0.029,-0.029,-0.032,-0.060,-0.177,-0.284,-0.394,0.000,1.000,0.0,0.000,1.000,0.0,0.000,1.000,0.0,0.000,1.000,0.0
75%,0.830,1.647,2.519,3.437,4.423,0.079,0.089,0.107,0.105,0.127,0.242,0.311,0.285,0.442,1.000,1.000,0.0,1.000,1.000,0.0,1.000,1.000,0.0,1.000,1.000,0.0
max,2.411,4.468,6.554,8.762,11.087,0.562,0.654,0.704,0.735,1.195,2.153,3.538,5.281,7.434,1.000,1.000,0.0,1.000,1.000,0.0,1.000,1.000,0.0,1.000,1.000,0.0

In [20]:
mean_spf_trim_nr.to_csv('cleaned_data/mean_spf_trim_nr.csv', sep=',', index=True)
ind_spf_trim_nr.to_csv('cleaned_data/ind_spf_trim_nr.csv', sep=',', index=True)