In [7]:
import os
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

os.chdir('/Users/fogellmcmuffin/Documents/thesis/_replication/')    # Working dir

mean_spf_trim = pd.read_csv('cleaned_data/mean_spf_trim.csv')
ind_spf_trim = pd.read_csv('cleaned_data/ind_spf_trim.csv')

mean_spf_trim = mean_spf_trim.set_index('DATE')
ind_spf_trim = ind_spf_trim.set_index(['DATE', 'ID'])
ind_spf_trim = ind_spf_trim.drop(['INDUSTRY'], axis=1)

###############################################
                ## SUM STATS ##
###############################################

def sumstats(df, end_date):
    df = df[:end_date]
    df = df.drop(['CPI1', 'CPI2', 'CPI3', 'CPI4', 'CPI5', 'CPI6', 'rec'], axis=1)
    df = df * 100
    for n in range(0,4):
        df[f'ru_t{n}'] = (df[f'r_t{n}'] > 0).astype(int)
        df[f'rd_t{n}'] = (df[f'r_t{n}'] < 0).astype(int)
        df[f'rn_t{n}'] = (df[f'r_t{n}'] == 0).astype(int)
    return df

# Data without recessions and COVID aftermath
def no_rec(df):
    a = df['2021-09-30':'2022-09-30']
    b = df[df['rec'] == 1]
    return df[(~df.index.isin(a.index)) & (~df.index.isin(b.index))]

ind_spf_trim_nr = no_rec(ind_spf_trim)
mean_spf_trim_nr = no_rec(mean_spf_trim)

ind_stats = sumstats(ind_spf_trim, '2016-12-31')
mean_stats = sumstats(mean_spf_trim, '2016-12-31')
ind_stats_nr = sumstats(ind_spf_trim_nr, '2016-12-31')
mean_stats_nr = sumstats(mean_spf_trim_nr, '2016-12-31')

ind_stats.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,3424.0000,3424.0000,3424.0000,3424.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000
mean,0.6525,1.3240,2.0224,2.7435,3.4854,-0.0291,-0.0610,-0.0846,-0.1055,-0.0165,-0.0582,-0.1323,-0.2218,-0.3315,0.3667,0.4346,0.0,0.3440,0.4208,0.0365,0.3389,0.4341,0.0283,0.3424,0.4383,0.0206
std,0.4398,0.7178,0.9978,1.2890,1.6027,0.3722,0.5148,0.6373,0.7559,0.4062,0.7798,1.0529,1.2829,1.5136,0.4820,0.4958,0.0,0.4751,0.4937,0.1876,0.4734,0.4957,0.1659,0.4746,0.4962,0.1420
min,-1.8652,-2.5966,-2.9689,-2.6505,-2.2175,-2.6500,-5.4112,-8.2931,-11.2801,-3.5020,-4.9244,-5.4703,-6.5677,-9.7573,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25%,0.4500,0.9521,1.4569,1.9884,2.5084,-0.1500,-0.2513,-0.3062,-0.3727,-0.2069,-0.4046,-0.6621,-0.8929,-1.1856,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50%,0.6500,1.2791,1.9120,2.5488,3.1897,-0.0000,-0.0162,-0.0254,-0.0264,-0.0149,-0.0323,-0.1277,-0.2725,-0.3689,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
75%,0.8500,1.6568,2.4700,3.3152,4.1678,0.1251,0.1759,0.1889,0.2062,0.2068,0.3713,0.4892,0.5162,0.5978,1.0000,1.0000,0.0,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000
max,2.9500,5.8326,9.0076,12.3596,15.8989,2.2250,4.3308,6.3570,8.2963,2.2350,3.3814,3.8011,4.8883,6.2129,1.0000,1.0000,0.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000

In [8]:
ind_stats_nr.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,3796.0000,3796.0000,3796.0000,3796.0000,3796.0000,3056.0000,3056.0000,3056.0000,3056.0000,3796.0000,3796.0000,3796.0000,3796.0000,3796.0000,3796.0000,3796.0000,3796.0,3796.0000,3796.0000,3796.0000,3796.0000,3796.0000,3796.0000,3796.0000,3796.0000,3796.0000
mean,0.6583,1.3343,2.0400,2.7698,3.5191,-0.0233,-0.0535,-0.0767,-0.0964,-0.0168,-0.0415,-0.0931,-0.1618,-0.2254,0.3630,0.4420,0.0,0.3398,0.4268,0.0385,0.3332,0.4410,0.0308,0.3390,0.4434,0.0227
std,0.3822,0.6578,0.9496,1.2575,1.5848,0.3206,0.4546,0.5841,0.7188,0.3440,0.6531,0.8850,1.1309,1.4413,0.4809,0.4967,0.0,0.4737,0.4947,0.1923,0.4714,0.4966,0.1729,0.4734,0.4968,0.1488
min,-1.6314,-1.5607,-1.2876,-0.9602,-0.7563,-2.6500,-5.4112,-8.2931,-11.2801,-1.6927,-3.7664,-5.0009,-6.5677,-9.7573,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25%,0.4640,0.9522,1.4570,1.9897,2.5250,-0.1500,-0.2283,-0.3034,-0.3576,-0.2070,-0.3807,-0.6117,-0.8067,-1.0537,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50%,0.6500,1.2790,1.9112,2.5351,3.1890,-0.0000,-0.0251,-0.0256,-0.0453,-0.0262,-0.0435,-0.1230,-0.2347,-0.3016,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
75%,0.8287,1.6316,2.4447,3.2898,4.1678,0.1250,0.1512,0.1771,0.2032,0.1732,0.3116,0.4445,0.4905,0.6587,1.0000,1.0000,0.0,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000
max,2.9500,5.8326,9.0076,12.3596,15.8989,2.2250,4.3308,6.3570,8.2963,2.2350,3.3814,3.8011,4.8883,6.2129,1.0000,1.0000,0.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000

In [2]:
mean_stats.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,142.0000,142.0000,142.0000,142.0000,142.0000,141.0000,141.0000,141.0000,141.0000,142.0000,142.0000,142.0000,142.0000,142.0000,142.0000,142.0000,142.0,142.0000,142.0000,142.0,142.0000,142.0000,142.0,142.0000,142.0000,142.0
mean,0.7210,1.4619,2.2329,3.0284,3.8482,-0.0263,-0.0604,-0.0886,-0.1164,-0.0180,-0.0642,-0.1478,-0.2535,-0.3829,0.4437,0.5493,0.0,0.4225,0.5704,0.0,0.4155,0.5775,0.0,0.4014,0.5915,0.0
std,0.3917,0.6754,0.9697,1.2759,1.5963,0.2534,0.3370,0.3975,0.4582,0.3081,0.6438,0.8806,1.0760,1.2829,0.4986,0.4993,0.0,0.4957,0.4968,0.0,0.4946,0.4957,0.0,0.4919,0.4933,0.0
min,-0.6342,-0.3955,-0.0341,0.4337,0.9158,-1.2034,-1.6884,-1.8574,-1.9183,-1.8190,-2.7290,-3.9056,-4.1162,-4.0459,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
25%,0.5175,1.0034,1.5433,2.1166,2.6746,-0.0980,-0.1545,-0.2136,-0.2943,-0.1583,-0.3357,-0.5346,-0.7441,-0.9753,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
50%,0.7150,1.3916,2.0658,2.7107,3.4155,-0.0162,-0.0316,-0.0512,-0.0637,-0.0267,-0.0560,-0.1601,-0.3057,-0.3964,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0
75%,0.8596,1.7069,2.6213,3.5798,4.5853,0.0777,0.0821,0.0980,0.1077,0.1485,0.2834,0.3222,0.2951,0.4696,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0
max,2.3156,4.3252,6.3497,8.3471,10.4006,0.7247,0.9643,1.0781,1.1494,0.6687,1.3703,2.0560,2.6623,2.8875,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0

In [9]:
mean_stats_nr.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,126.0000,126.0000,126.0000,126.0000,126.0000,125.0000,125.0000,125.0000,125.0000,126.0000,126.0000,126.0000,126.0000,126.0000,126.0000,126.0000,126.0,126.0000,126.0000,126.0,126.0000,126.0000,126.0,126.0000,126.0000,126.0
mean,0.7163,1.4576,2.2327,3.0342,3.8587,-0.0300,-0.0660,-0.0945,-0.1203,-0.0232,-0.0665,-0.1398,-0.2327,-0.3291,0.4365,0.5556,0.0,0.4127,0.5794,0.0,0.3968,0.5952,0.0,0.3889,0.6032,0.0
std,0.3499,0.6373,0.9445,1.2640,1.5965,0.2113,0.2785,0.3392,0.4065,0.2637,0.5418,0.7363,0.9453,1.2304,0.4979,0.4989,0.0,0.4943,0.4956,0.0,0.4912,0.4928,0.0,0.4894,0.4912,0.0
min,-0.3627,0.0320,0.5258,1.0183,1.5300,-0.7884,-1.1050,-1.4215,-1.7292,-0.7225,-2.0181,-2.6869,-3.1003,-4.0459,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
25%,0.5033,0.9991,1.5381,2.1123,2.6643,-0.0987,-0.1545,-0.2136,-0.2943,-0.1583,-0.2963,-0.5133,-0.6984,-0.9412,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
50%,0.6933,1.3897,2.0658,2.7107,3.4155,-0.0162,-0.0319,-0.0587,-0.0667,-0.0446,-0.0649,-0.1722,-0.3018,-0.3937,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0
75%,0.8369,1.6606,2.5912,3.5492,4.5255,0.0556,0.0713,0.0747,0.0922,0.1262,0.2085,0.3022,0.2806,0.4696,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0
max,2.3156,4.3252,6.3497,8.3471,10.4006,0.5661,0.6550,0.7056,0.7501,0.6687,1.3703,1.7226,2.0084,2.8875,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0

In [10]:
mean_spf_trim_nr.to_csv('cleaned_data/mean_spf_trim_nr.csv', sep=',', index=True)
ind_spf_trim_nr.to_csv('cleaned_data/ind_spf_trim_nr.csv', sep=',', index=True)