In [9]:
import os
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

os.chdir('/Users/fogellmcmuffin/Documents/thesis/_replication/')    # Working dir

mean_spf_trim = pd.read_csv('cleaned_data/mean_spf_trim.csv')
ind_spf_trim = pd.read_csv('cleaned_data/ind_spf_trim.csv')

mean_spf_trim = mean_spf_trim.set_index('DATE')
ind_spf_trim = ind_spf_trim.set_index(['DATE', 'ID'])
ind_spf_trim = ind_spf_trim.drop(['INDUSTRY'], axis=1)

###############################################
                ## SUM STATS ##
###############################################

def sumstats(df, end_date):
    df = df[:end_date]
    df = df.drop(['CPI1', 'CPI2', 'CPI3', 'CPI4', 'CPI5', 'CPI6', 'rec'], axis=1)
    df = df * 100
    for n in range(0,4):
        df[f'ru_t{n}'] = (df[f'r_t{n}'] > 0).astype(int)
        df[f'rd_t{n}'] = (df[f'r_t{n}'] < 0).astype(int)
        df[f'rn_t{n}'] = (df[f'r_t{n}'] == 0).astype(int)
    return df


# Data without business cycles
def no_rec(df):
    a = df['2021-09-30':'2022-09-30']
    b = df[df['rec'] == 1]
    return df[(~df.index.isin(b.index)) & (~df.index.isin(a.index))]


ind_spf_trim_nr = no_rec(ind_spf_trim)
mean_spf_trim_nr = no_rec(mean_spf_trim)

date = '2020-06-30'

ind_stats = sumstats(ind_spf_trim, date)
mean_stats = sumstats(mean_spf_trim, date)
ind_stats_nr = sumstats(ind_spf_trim_nr, date)
mean_stats_nr = sumstats(mean_spf_trim_nr, date)

In [10]:
print(f"Number of Unique Forecasters: {ind_spf_trim[:date].index.get_level_values('ID').nunique()}")
print(f"Average Forecaster per Forecaster: {np.mean(ind_spf_trim[:date].groupby(level='ID').size())}")

Number of Unique Forecasters: 134
Average Forecaster per Forecaster: 35.1865671641791

In [11]:
ind_stats.describe().round(2)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,4715.00,4715.00,4715.00,4715.00,4715.00,3775.00,3775.00,3775.00,3775.00,4715.00,4715.00,4715.00,4715.00,4715.00,4715.00,4715.00,4715.0,4715.00,4715.00,4715.00,4715.00,4715.00,4715.00,4715.00,4715.00,4715.00
mean,0.63,1.29,1.98,2.68,3.41,-0.04,-0.07,-0.09,-0.11,-0.02,-0.07,-0.15,-0.23,-0.32,0.36,0.44,0.0,0.34,0.42,0.04,0.34,0.44,0.03,0.34,0.44,0.02
std,0.44,0.70,0.96,1.24,1.54,0.37,0.49,0.58,0.67,0.39,0.75,1.01,1.22,1.45,0.48,0.50,0.0,0.47,0.49,0.19,0.47,0.50,0.17,0.47,0.50,0.14
min,-2.07,-2.74,-3.04,-2.72,-2.29,-2.88,-4.04,-5.05,-5.49,-3.60,-5.03,-5.58,-6.54,-9.76,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.45,0.93,1.45,1.96,2.50,-0.16,-0.23,-0.30,-0.36,-0.20,-0.42,-0.66,-0.87,-1.12,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,0.62,1.25,1.85,2.47,3.10,-0.00,-0.02,-0.03,-0.03,-0.02,-0.04,-0.15,-0.27,-0.36,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,0.82,1.61,2.42,3.22,4.04,0.12,0.15,0.18,0.20,0.19,0.35,0.45,0.47,0.52,1.00,1.00,0.0,1.00,1.00,0.00,1.00,1.00,0.00,1.00,1.00,0.00
max,2.95,5.83,9.01,12.36,15.90,3.00,3.45,3.48,4.54,1.49,2.87,3.53,4.38,5.91,1.00,1.00,0.0,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [12]:
ind_stats_nr.describe().round(2)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,4170.00,4170.00,4170.00,4170.00,4170.00,3352.00,3352.00,3352.00,3352.00,4170.00,4170.00,4170.00,4170.00,4170.00,4170.00,4170.00,4170.0,4170.00,4170.00,4170.00,4170.00,4170.00,4170.00,4170.00,4170.00,4170.00
mean,0.65,1.32,2.01,2.72,3.46,-0.02,-0.05,-0.07,-0.09,-0.02,-0.05,-0.12,-0.19,-0.26,0.36,0.44,0.0,0.34,0.42,0.04,0.33,0.44,0.03,0.34,0.44,0.02
std,0.37,0.62,0.90,1.19,1.50,0.30,0.40,0.50,0.60,0.33,0.62,0.85,1.07,1.36,0.48,0.50,0.0,0.47,0.49,0.19,0.47,0.50,0.18,0.47,0.50,0.15
min,-1.63,-1.56,-1.29,-0.88,-0.94,-2.25,-3.40,-4.32,-5.49,-1.81,-3.30,-5.00,-6.54,-9.76,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.45,0.95,1.46,1.99,2.53,-0.15,-0.23,-0.28,-0.33,-0.20,-0.39,-0.61,-0.79,-1.03,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,0.62,1.25,1.86,2.48,3.11,-0.00,-0.02,-0.03,-0.03,-0.02,-0.05,-0.14,-0.24,-0.32,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,0.82,1.61,2.39,3.21,4.04,0.12,0.15,0.18,0.19,0.17,0.29,0.40,0.44,0.53,1.00,1.00,0.0,1.00,1.00,0.00,1.00,1.00,0.00,1.00,1.00,0.00
max,2.95,5.83,9.01,12.36,15.90,1.70,2.38,3.48,4.54,1.49,2.42,3.38,4.38,5.91,1.00,1.00,0.0,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [13]:
mean_stats.describe().round(2)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,156.00,156.00,156.00,156.00,156.00,155.00,155.00,155.00,155.00,156.00,156.00,156.00,156.00,156.00,156.00,156.00,156.0,156.00,156.00,156.0,156.00,156.00,156.0,156.00,156.00,156.0
mean,0.70,1.43,2.18,2.96,3.76,-0.03,-0.07,-0.09,-0.12,-0.02,-0.08,-0.16,-0.27,-0.38,0.43,0.56,0.0,0.43,0.56,0.0,0.42,0.58,0.0,0.41,0.58,0.0
std,0.40,0.68,0.98,1.28,1.61,0.26,0.34,0.40,0.46,0.30,0.64,0.87,1.06,1.28,0.50,0.50,0.0,0.50,0.50,0.0,0.49,0.50,0.0,0.49,0.49,0.0
min,-0.67,-0.45,-0.05,0.39,0.86,-1.21,-1.72,-1.88,-2.01,-1.82,-2.73,-3.91,-4.12,-4.95,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0
25%,0.49,0.99,1.53,2.12,2.68,-0.09,-0.15,-0.21,-0.27,-0.16,-0.34,-0.56,-0.75,-0.97,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0
50%,0.68,1.33,1.94,2.58,3.20,-0.01,-0.03,-0.05,-0.05,-0.03,-0.06,-0.18,-0.31,-0.42,0.00,1.00,0.0,0.00,1.00,0.0,0.00,1.00,0.0,0.00,1.00,0.0
75%,0.84,1.67,2.58,3.51,4.50,0.08,0.09,0.10,0.10,0.14,0.28,0.32,0.29,0.30,1.00,1.00,0.0,1.00,1.00,0.0,1.00,1.00,0.0,1.00,1.00,0.0
max,2.41,4.47,6.55,8.76,11.09,0.72,0.96,1.08,1.15,0.67,1.37,2.06,2.66,2.88,1.00,1.00,0.0,1.00,1.00,0.0,1.00,1.00,0.0,1.00,1.00,0.0

In [14]:
mean_stats_nr.describe().round(2)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,138.00,138.00,138.00,138.00,138.00,137.00,137.00,137.00,137.00,138.00,138.00,138.00,138.00,138.00,138.00,138.00,138.0,138.00,138.00,138.0,138.00,138.00,138.0,138.00,138.00,138.0
mean,0.71,1.44,2.20,2.98,3.79,-0.03,-0.06,-0.09,-0.11,-0.03,-0.08,-0.16,-0.26,-0.36,0.43,0.57,0.0,0.43,0.57,0.0,0.41,0.58,0.0,0.41,0.59,0.0
std,0.35,0.64,0.94,1.27,1.60,0.21,0.27,0.33,0.40,0.26,0.53,0.73,0.94,1.22,0.50,0.50,0.0,0.50,0.50,0.0,0.49,0.50,0.0,0.49,0.49,0.0
min,-0.39,-0.01,0.47,1.00,1.51,-0.81,-1.10,-1.44,-2.01,-0.74,-1.92,-2.69,-3.10,-4.95,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0
25%,0.50,0.99,1.53,2.12,2.70,-0.10,-0.15,-0.21,-0.26,-0.15,-0.30,-0.53,-0.70,-0.91,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0
50%,0.66,1.28,1.90,2.53,3.20,-0.01,-0.03,-0.04,-0.05,-0.04,-0.07,-0.19,-0.31,-0.41,0.00,1.00,0.0,0.00,1.00,0.0,0.00,1.00,0.0,0.00,1.00,0.0
75%,0.83,1.64,2.55,3.45,4.44,0.07,0.08,0.08,0.10,0.13,0.20,0.30,0.27,0.28,1.00,1.00,0.0,1.00,1.00,0.0,1.00,1.00,0.0,1.00,1.00,0.0
max,2.41,4.47,6.55,8.76,11.09,0.56,0.65,0.70,0.73,0.67,1.37,1.72,2.01,2.88,1.00,1.00,0.0,1.00,1.00,0.0,1.00,1.00,0.0,1.00,1.00,0.0

In [15]:
mean_spf_trim_nr.to_csv('cleaned_data/mean_spf_trim_nr.csv', sep=',', index=True)
ind_spf_trim_nr.to_csv('cleaned_data/ind_spf_trim_nr.csv', sep=',', index=True)